spring:
  application:
    name: notification-service

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

server:
  port: 8083

logging:
  level:
    root: INFO
    com.johncarrieta2.notificationservice: DEBUG
    org.springframework: WARN
    org.springframework.boot.autoconfigure: ERROR

  file:
    name: logs/notification-service.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level [%thread] %logger{36} - %msg%n"

aws:
  region: us-east-1
  credentials:
    access-key: test
    secret-key: test
  sqs:
    endpoint: http://localhost:4566
    queue-name: payment-notifications
    queue-url: http://localhost:4566/000000000000/payment-notifications
  dynamodb:
    endpoint: http://localhost:4566
    table-name: Notifications
